# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mountain Club Cheers
email:
description:
baseurl: "/mountain-club-cheers" # the subpath of your site, e.g. /blog
url: "" # the base hostname &jekyllrb
destination: 'docs'

github_username:  vasilivanov93

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - .gitignore
  - scss
  - gulpfile.js